### ISSUE TITLE
There's a tremendous lag with notifications. Look at the video on Slack.

### ISSUE THREAD

**Issue by MattiasJay** [Skjutsgruppen/skjutsgruppen-reactnative#542] opened 2018-11-18 20:12 UTC
There's a tremendous lag with notifications. Look at the video on Slack. It's not just about me waiting, it's just not anything happening. Look to the end and you'll see the lag where "new" suddenly pops up. Also, the small blue "notifications ball" next to the speech bubbles doesn't seem do disappear after I've checked my new notifications.

**Comment by anjesh** [comment] 2019-03-06 09:22
Duplicate of https://github.com/Skjutsgruppen/skjutsgruppen-reactnative/issues/565

**Closed as completed by anjesh** 2019-03-06 09:22 UTC
